service: aws-remote-websocket-serverless

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.12
  stage: ${opt:stage, 'dev'}
  region: eu-central-1
  timeout: 60

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "dynamodb:GetItem"
            - "dynamodb:PutItem"
            - "dynamodb:UpdateItem"
            - "dynamodb:DeleteItem"
            - "dynamodb:Scan"
          Resource:
            - { "Fn::GetAtt": ["ClientsTable", "Arn"] }

        - Effect: Allow
          Action:
            - "dynamodb:GetItem"
            - "dynamodb:PutItem"
            - "dynamodb:UpdateItem"
            - "dynamodb:DeleteItem"
            - "dynamodb:Scan"
          Resource:
            - { "Fn::GetAtt": ["IRRemotes", "Arn"] }

        - Effect: Allow
          Action:
            - "dynamodb:ConditionCheckItem"
            - "dynamodb:GetItem"
            - "dynamodb:PutItem"
            - "dynamodb:UpdateItem"
            - "dynamodb:DeleteItem"
            - "dynamodb:Scan"
            - "dynamodb:Query"
          Resource:
            - { "Fn::GetAtt": ["IoTDevices", "Arn"] }

  environment: 
    CLIENTS_TABLE_NAME: ${self:provider.stage}WSClients
    REMOTES_TABLE_NAME: ${self:provider.stage}IRRemotes
    IOT_DEVICES_TABLE_NAME: ${self:provider.stage}IoTDevices
    WSSAPIGATEWAYENDPOINT:
      Fn::Join:
        - ""
        - - "https://"
          - Ref: WebsocketsApi
          - ".execute-api."
          - Ref: AWS::Region
          - ".amazonaws.com/${sls:stage}"


functions:
  websocketHandler:
    handler: src/websockets_router.handle
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect
      - websocket:
          route: msg

  httpDataHandler:
    handler: src/http_router.handle
    events:
      - httpApi:
          path: /api/remotes
          method: GET
      - httpApi:
          path: /api/remotes/{remoteName}
          method: GET
      - httpApi:
          path: /api/devices
          method: GET
      - httpApi:
          path: /api/devices/{macAddress}
          method: GET
      - httpApi:
          path: /api/devices/connected
          method: GET
  


plugins:
  - serverless-python-requirements

resources:
  Resources:
    ClientsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.CLIENTS_TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: connectionId
            AttributeType: S
        KeySchema:
          - AttributeName: connectionId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 2
          WriteCapacityUnits: 2

    IRRemotes:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.REMOTES_TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: remoteName
            AttributeType: S
        KeySchema:
          - AttributeName: remoteName
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 2
          WriteCapacityUnits: 2

    IoTDevices:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.IOT_DEVICES_TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: macAddress
            AttributeType: S
        KeySchema:
          - AttributeName: macAddress
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 2
          WriteCapacityUnits: 2
